### ISSUE TITLE
start coordinate to deleted sequence conversion

### ISSUE THREAD

**Issue by epaule** [alliance-genome/agr_file_generator#19]
`    {
      "alleleId": "FB:FBal0031493",
      "assembly": "R6.28",
      "chromosome": "3R",
      "end": 4346199,
      "genomicVariantSequence": "N/A",
      "paddedBase": "T",
      "references": [
        {
          "crossReference": {
            "id": "FB:FBrf0072695",
            "pages": [
              "reference"
            ]
          },
          "publicationId": "PMID:8208294"
        }
      ],
      "sequenceOfReferenceAccessionNumber": "RefSeq:NT_033777.3",
      "start": 4345885,
      "type": "SO:0000159"
    },
`
got converted into 
`
3R	4345885	NT_033777.3:g.4345885_4346199del	TTGTTGGAGAAGGCCACGTCGCAGTTGGGGCACTTGAACTTCTTCGGCCGCTGCTTGCGGCTGTTGAGCGCCTTTAACTGTGCGTCCTCGGCCATCACGCGGGCGTACTCTTGCTCCATCAGGCCCATAGTGAACGGGTCCATGCCGAAGCCCGGGACGGCAGTGGGCGTGGAGGCAGCAGCGGCTGCTGCGGCGGCGGCAGCGTAGTAGAGATCGCTGGCGGCCGACAGGAATGGAGCGTGCTGGTTTGGCGGAGCCAAGGATGCGGTGGCGGCGGCGTGCGTGTCCAACGGCGACGACTGCGGGTGTGAAAAGA	T	.	.	hgvs_nomenclature="NT_033777.3:g.4345885_4346199del";symbol="hkb<sup>1</sup>";allele_of_genes="FB:FBgn0261434"
`

but of course TTGTT would be the sequence from 4345884 on, meaning it is a bp off (as in: you included the padding base).
The VCF data was R6.27-2.3.0.vcf from the 22nd of August.

**Comment by epaule** [comment]
seems like it is allowed in the spec. Will need to check with the VEP guys.
M

**Comment by epaule** [comment]
FOr the VCF you need to deduct one from POS in cases where you include a padding base.

from http://samtools.github.io/hts-specs/VCFv4.1.pdf
For simple insertions and deletions in which either the REF or one of the ALT alleles would otherwise be null/empty, the REF and ALT Strings must include the base before the event (which must be reflected in the POS field), unless the event occurs at position 1 on the contig in which case it must include the base after the event;

**Comment by nuin** [comment]
@epaule I am still a little bit confused with this issues, mostly because I don't have the  R6.27-2.3.0.vcf from August (anywhere I can find it? How was it generated?). Would you mind posting a couple of more examples with ideal solutions? 

Also, do you need a VCF to run VEP or a list of HVGS locations would be enough?

**Comment by gildossantos** [comment]
Do the input FB VARIATION files need to be fixed?

**Comment by epaule** [comment]
If with input you mean the JSON files being submitted through the FSM, then no. 
But if you mean the input VCF files I used for the VEP, then yes. I basically have to rerun it for each species with deletions.

**Comment by nuin** [comment]
@epaule Adding the VCFs to the S3 bucket. For that specific variant I see this now

```../output/R6-2.3.0.vcf:3R	4345884	NT_033777.3:g.4345885_4346199del	TTGTTGGAGAAGGCCACGTCGCAGTTGGGGCACTTGAACTTCTTCGGCCGCTGCTTGCGGCTGTTGAGCGCCTTTAACTGTGCGTCCTCGGCCATCACGCGGGCGTACTCTTGCTCCATCAGGCCCATAGTGAACGGGTCCATGCCGAAGCCCGGGACGGCAGTGGGCGTGGAGGCAGCAGCGGCTGCTGCGGCGGCGGCAGCGTAGTAGAGATCGCTGGCGGCCGACAGGAATGGAGCGTGCTGGTTTGGCGGAGCCAAGGATGCGGTGGCGGCGGCGTGCGTGTCCAACGGCGACGACTGCGGGTGTGAAAAGA	T	.	.	hgvs_nomenclature="NT_033777.3:g.4345885_4346199del";geneLevelConsequence="stop lost,inframe deletion";symbol="hkb<sup>1</sup>";alleles="FB:FBal0031493";allele_of_genes="FB:FBgn0261434";symbol_text="hkb<1>"```

Let me know

**Comment by epaule** [comment]
looking good: https://www.ensembl.org/Drosophila_melanogaster/Tools/VEP/Results?tl=Y4kYMZ7HCSRjmalI-5670052

could you redump the whole collected species VCF files?

**Comment by nuin** [comment]
We generated all file at the same time.

**Comment by epaule** [comment]
@nuin could it be that the download location changed? Because the ones below are still the old files

- https://mod-datadumps.s3.amazonaws.com/generated-files/GRCz11-2.3.0.vcf
- https://mod-datadumps.s3.amazonaws.com/generated-files/R6.27-2.3.0.vcf
- https://mod-datadumps.s3.amazonaws.com/generated-files/GRCm38-2.3.0.vcf
- https://mod-datadumps.s3.amazonaws.com/generated-files/Rnor_6.0-2.3.0.vcf
- https://mod-datadumps.s3.amazonaws.com/generated-files/WBcel235-2.3.0.vcf

**Comment by a8wright** [comment]
@epaule 

There is some additional code in the repo that removes "." and "_" from the assembly names. Also R6.27 is changed to R6 as the ".27" part doesn't mean anything and changes every so often (will be fixed from the FlyBase side sometime soon. 

This doesn't solve why all of those are not new. According to S3, these files were last updated on Sept 25th, 2019:
https://mod-datadumps.s3.amazonaws.com/generated-files/WBcel235-2.3.0.vcf
https://mod-datadumps.s3.amazonaws.com/generated-files/R6-2.3.0.vcf
https://mod-datadumps.s3.amazonaws.com/generated-files/GRCz11-2.3.0.vcf
https://mod-datadumps.s3.amazonaws.com/generated-files/GRCm38-2.3.0.vcf
https://mod-datadumps.s3.amazonaws.com/generated-files/Rnor60-2.3.0.vcf

Hope this helps

**Comment by epaule** [comment]
thansk @a8wright , can you guys shout when you updated them ?

**Comment by epaule** [comment]
actually the ones with the corrected name look good. Will do another round of VEPing with them

**Comment by nuin** [comment]
I posted on Slack mentioning you @epaule and updated the ticket almost at the same time when we updated them. Whenever it happens it the future I will post on Slack.

**Comment by epaule** [comment]
@nuin I did see your slack post, but as i pulled the RGD and FB files with the old names (which are still on the bucket with the old data), I assumed they weren't updated as I can't list the other files.

**Comment by a8wright** [comment]
@epaule Sorry about this process. We are going through a transition where these files will be getting submitted to the File Management System. When it is integrated the files will be updated every time the code or database is. You will have a consistent endpoint to get the latest file. They will also be added to the downloads page and should show the date they were last updated there. We will try to keep you up to date as changes are made.

**Comment by nuin** [comment]
@epaule If this issue is solved in your end, would you mind closing it? Thanks
